name: faultstat
summary: tool to measure page faults
description: faultstat measures page fault activity and swap utilization of processes
confinement: strict
grade: stable
assumes: [snapd2.45]
base: core18
adopt-info: faultstat

environment:
    CFLAGS: '-fstack-protector-strong -Wformat -Werror=format-security'
    LDFLAGS: Wl,-z,relro

parts:
    faultstat:
        plugin: make
        source: https://github.com/ColinIanKing/faultstat.git
        source-type: git
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make
            - libncurses-dev
            - libncursesw5-dev
        stage-packages:
            - libncurses-dev
            - libncursesw5-dev

apps:
    faultstat:
        plugs: [ home, system-observe ]
        command: usr/bin/faultstat
